type Category {
    id: ID!
    name: String!
    images: String
    products: [Product]
}

type Product {
    id: ID!
    title: String!
    quantity: Int
    description: String
    images: String
    price: Float
    category: Category
}

input CategoryInput {
    name: String!
    images: String
}

input ProductInput {
    title: String!
    quantity: Int
    description: String
    images: String
    price: Float
    categoryId: ID!
}

type Query {
    getAllCategories: [Category]
    getCategoryById(id: ID!): Category
    getAllProducts: [Product]
    getProductById(id: ID!): Product
    
    # Hiển thị tất cả product có price từ thấp đến cao
    getProductsSortedByPrice: [Product]
    
    # Lấy tất cả product của 01 category
    getProductsByCategory(categoryId: ID!): [Product]
}

type Mutation {
    # Category CRUD
    createCategory(input: CategoryInput!): Category
    updateCategory(id: ID!, input: CategoryInput!): Category
    deleteCategory(id: ID!): Boolean
    
    # Product CRUD
    createProduct(input: ProductInput!): Product
    updateProduct(id: ID!, input: ProductInput!): Product
    deleteProduct(id: ID!): Boolean
}
